### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'method'

### ISSUE THREAD

**Issue by sbansla** [inyutin/aiohttp_retry#107]
We are receiving below error on running our test cases after the upgrade.
Is there any breaking change in 2.9.0 because of [PR](https://github.com/inyutin/aiohttp_retry/pull/103/files#diff-7027d072f17c0637f41af49ed64023fd93d6484df689a8a3ac2472c8202a1ba8R92)

async def _is_skip_retry(self, current_attempt: int, response: ClientResponse) -> bool:
--
  | if current_attempt == self._retry_options.attempts:
  | return True
  |  
  | >       if response.method not in self._retry_options.methods:
  | E       AttributeError: 'MockResponse' object has no attribute 'method'

**Comment by inyutin** [comment]
Hello! This is the PR that was merged:
https://github.com/inyutin/aiohttp_retry/commit/723961d3c2e841da8232b2da92e354c70624310c
It seems related 

I'm not sure of your test setup, but basically the code now checks what HTTP method the url was called with. It's taking the method from the response. It seems in your test setup, you replace Response with MockResponse. The "MockResponse" should have "method" attribute
