### ISSUE TITLE
Change URL between retries ?

### ISSUE THREAD

**Issue by eLvErDe** [inyutin/aiohttp_retry#23]
Hello,

I tried to use your module however I couldn't find a way to switch URL from one host to another between retries which sadly renders the module useless to me.

Do you have any idea how I could do that ? I tried to use on_request_start callback but params object is frozen, and I doubt it's aimed to be re-used later anyway even if it could be mutated.

Thanks in advance,

Adam.

**Comment by inyutin** [comment]
@eLvErDe 

Sorry for long response, but I finally got good news for you. I implemented logic to switch url in v2.3.2
See: https://github.com/inyutin/aiohttp_retry#change-url-between-retries

**Comment by eLvErDe** [comment]
Thats indeed a very good news, thanks a lot for that :)
