### ISSUE TITLE
How to change the parameters in the second attempt?

### ISSUE THREAD

**Issue by lixiaolong41** [inyutin/aiohttp_retry#38]
For example, if the first attempt is unsuccessful, change the parameter proxy and try again

**Comment by inyutin** [comment]
@lixiaolong41 hello. You can do it now, with version >= 2,8,0
See an example in readme

**Comment by denisolyanyuk** [comment]
Not very convenient: for example I don't know which proxies would be available at the time of retry. 
I think some callback like `before_retry` would be more flexible
