### ISSUE TITLE
Feature request: allow defaults to be set at construction time

### ISSUE THREAD

**Issue by bmerry** [inyutin/aiohttp_retry#4]
First, thanks for this library - it's just saved me implementing some of this logic myself.

It would be helpful if one could set the parameters on the class, rather than in each method call. That way library code that expects to receive an aiohttp.ClientSession could be passed a RetryClient instead (as long as it limits itself to the methods that RetryClient implements) and it wouldn't need to modify every HTTP call. In my case I want to retry on connection errors, so I have to pass `retry_exceptions={aiohttp.ClientError}` all over the place.

**Comment by inyutin** [comment]
Thanks for suggestion!

I agreed that this is useful and implemented with v2.0. Be aware: it doesn't have backward compatibility. You can find new examples of usage at [Readme.md](https://github.com/inyutin/aiohttp_retry#examples-of-usage).

I'm sorry for not answering such a long time.

**Comment by bmerry** [comment]
Thanks! Will check it out at some point.
