### ISSUE TITLE
Add URL type usage in requests

### ISSUE THREAD

**Issue by churnikov** [inyutin/aiohttp_retry#41]
I've encountered a bug, that I cannot use yarl URL type with your library.

This is due to [this line](https://github.com/inyutin/aiohttp_retry/blob/b41dd3022d3dbac3e97456d694bff888d4d87a91/aiohttp_retry/__init__.py#L191), where you allow usage of strings.

This seems like an easy fix, I could look into during this weekend

**Comment by inyutin** [comment]
Sorry for not answering before.
I add support for YARL URL: https://github.com/inyutin/aiohttp_retry/pull/45
I will notified additionally, when it would be released.

**Comment by inyutin** [comment]
Released 🎉 
Consider using v2.4.5
