### ISSUE TITLE
Feature request: FibonacciRetry + jitter options

### ISSUE THREAD

**Issue by susliko** [inyutin/aiohttp_retry#44]
I have 2 proposals:
1. In some cases it might be convenient to have retry pauses growing slower than exponent. Fibonacci sequence might be an option
2. In case of multiple simultaneous requests they will be also retried simultaneously. In order to mitigate this issue we might add some jitter, e.g.:
instead of sleeping for `base * (2 ** i)` we might sleep `base * (2 ** i) +- random(0, k) * base, k < 0` in order to spread retrying clients in time

**Comment by inyutin** [comment]
Sorry for not answering before.
I add both fibonacci and jitter retry patterns: https://github.com/inyutin/aiohttp_retry/pull/47
I will notified additionally, when it would be released.

**Comment by inyutin** [comment]
Released 🎉 
Consider using v2.4.5
