### ISSUE TITLE
Change headers between requests 

### ISSUE THREAD

**Issue by vToMy** [inyutin/aiohttp_retry#48]
I use jwt in header to authenticate as client. However after some retries the token expires and retrying will fail unless I update the token.
Is it possible to add changing headers on retrying?
I think being able to alter the request object itself would be the most flexable solution.

**Comment by dnovmp** [comment]
+1
I second it.

**Comment by inyutin** [comment]
@vToMy @dnovmp I'm working on it. I'm planning you would be able to pass requests list, as currently you can pass list of urls. I will present this soon

**Comment by inyutin** [comment]
@dnovmp @vToMy 
You can do it now! Update to v2.8.0

**Comment by inyutin** [comment]
Example from readme:
```python
from aiohttp_retry import RetryClient, RequestParams, ExponentialRetry

async def main():
    retry_client = RetryClient(raise_for_status=False)

    async with retry_client.requests(
        params_list=[
            RequestParams(
                method='GET',
                path='https://ya.ru',
            ),
            RequestParams(
                method='GET',
                path='https://ya.ru',
                headers={'some_header': 'some_value'},
            ),
        ]
    ) as response:
        print(response.status)
        
    await retry_client.close()
```
