### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by kof0012** [inyutin/aiohttp_retry#51]
HI,when i use A simple example like this ，then， make many mistake 。。。

```
async def main():
 retry_options = ExponentialRetry(attempts=1)
    retry_client = RetryClient(raise_for_status=False, retry_options=retry_options,auth=aiohttp.BasicAuth(login="gitusers", password="okpass"),connector=aiohttp.TCPConnector(verify_ssl=False))
    async with retry_client.post('https://somewebs.com',json=fhzd) as response:
        print(response.status)
        print(await response.text())
    await retry_client.close()

asyncio.run(main())

```

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000024AB8FA0550>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Savlik** [comment]
Hi, this is a general python/windows problem. Bug tracking here: https://bugs.python.org/issue39232

**Comment by inyutin** [comment]
@kof0012 as Savlik suggested there is probably general problem with python on windows. 
The only solution I can suggest is to try use loop explicit:
```python
import asyncio
from aiohttp_retry import RetryClient, ExponentialRetry

async def main():
    retry_options = ExponentialRetry(attempts=1)
    retry_client = RetryClient(raise_for_status=False, retry_options=retry_options)
    async with retry_client.get('https://ya.ru') as response:
        print(response.status)

    await retry_client.close()


loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
loop.run_until_complete(main())
```
