### ISSUE TITLE
Documentation on types of Exception that can be thrown

### ISSUE THREAD

**Issue by KevinLinSL** [inyutin/aiohttp_retry#52]
I'd appreciate some clarity on what Exceptions are thrown when in the Readme. Specifically, does an exception get raised when the maximum retries are exceeded? Is this an aiohttp.ClientResponseError, or something else?

**Comment by inyutin** [comment]
@KevinLinSL  Hi!

Actually the last response will be returned. If last request ended with exception that it will be re-raised from RetryClient side.
Updated Readme, so I hope it will be much easy to understand
https://github.com/inyutin/aiohttp_retry/commit/583acd1663a26f1bfdb186b9ab9a54214f8ae413
