### ISSUE TITLE
Current attempt debug log message may be misleading

### ISSUE THREAD

**Issue by wojciechwroblewski** [inyutin/aiohttp_retry#54]
At the moment, turning on debug logging returns misleading information about the attempts, e.g.
```
DEBUG:aiohttp_retry:Attempt 0 out of 5
DEBUG:aiohttp_retry:Attempt 1 out of 5
DEBUG:aiohttp_retry:Attempt 2 out of 5
DEBUG:aiohttp_retry:Attempt 3 out of 5
DEBUG:aiohttp_retry:Attempt 4 out of 5
Traceback (most recent call last):
...
```
Then the client is done retrying, but the last message was `Attempt 4 out of 5`. I was bit confused first time seeing that.  

Technically, this could be easily fixed by incrementing the value being displayed, however I'm wondering if that's the right way. In fact, the client starts with first attempt, so aligning it by setting [`current_attempt = 1`](https://github.com/inyutin/aiohttp_retry/blob/master/aiohttp_retry/client.py#L62) at the beginning would make sense. WDYT?

**Comment by inyutin** [comment]
@wojciechwroblewski fix it, update to v2.4.8
https://github.com/inyutin/aiohttp_retry/commit/c98d065da5a5c3dd0da17272d23af5c3b59f2c0e
