### ISSUE TITLE
Feature Request: allow user to pass in custom ClientSession

### ISSUE THREAD

**Issue by kirkhansen** [inyutin/aiohttp_retry#60]
I'd like to make use of https://github.com/JWCook/aiohttp-client-cache which subclasses the `ClientSession`. I think the easiest path forward would be to pass in the cached session object when creating a `RetryClient`.

**Comment by inyutin** [comment]
@kirkhansen Hello!
It's possible now, look this commit for an example
https://github.com/inyutin/aiohttp_retry/commit/14b8541508a286a898df4d3aa7957f1a50875f55

Use >= 2.5.4v.
