### ISSUE TITLE
Formdata already processed by Retry on status 429

### ISSUE THREAD

**Issue by wreggyl** [inyutin/aiohttp_retry#61]
we have an endpoint where we upload files / comments as formdata.

we call ClientSession Post from RetryClient with Formdata object as value for data

`form_data = FormData()
form_data.add_field('comment', text, content_type="multipart/form-data")`

and this is directly send as data=form_data

In good case everything is work fine, but if the server rates limit us with a 429 the RetryClient retry our call and we get the exception:

`self = <aiohttp.formdata.FormData object at 0x000001BE7C630670>

    def _gen_form_data(self) -> multipart.MultipartWriter:
        """Encode a list of fields using the multipart/form-data MIME format"""
        if self._is_processed:
>           raise RuntimeError("Form data has been processed already")
E           RuntimeError: Form data has been processed already`

Any idea how to solve this?

Thx in advance

**Comment by outgaze** [comment]
First, why are you definitely content-type?
You should instead read the response first using .read() and then attempt to grab whatever information you're trying to grab using the appropriate .text() or .json() that's a very common problem with server responses as it sometimes servers tend to return data with different content type but same format.

**Comment by inyutin** [comment]
@wreggyl hi!

This is a problem on aiohttp side. Please, see this issue: https://github.com/aio-libs/aiohttp/issues/5577
There is also a fixed for it, but it seems to be forgotten: https://github.com/aio-libs/aiohttp/pull/5583
I will try to gently bump this discussion once again now. 

Unfortunately, there is nothing I can do on aiohttp-retry side, so I will close the issue.

**Comment by lososkin** [comment]
You can use MultipartWriter instead of FormData

**Comment by witoong623** [comment]
This is what I ended up doing in order to fix it.
```
from aiohttp import FormData

class RepeatableFormData(FormData):
    def __call__(self):
        if self._is_multipart:
            if self._is_processed:
                return self._writer

            return self._gen_form_data()
        else:
            return self._gen_form_urlencoded()
```
Accroding to [MultipartWriter](https://docs.aiohttp.org/en/stable/multipart.html) document:

> Please note, that on [MultipartWriter.write()](https://docs.aiohttp.org/en/stable/multipart_reference.html#aiohttp.MultipartWriter.write) all the file objects will be read until the end and there is no way to repeat a request without rewinding their pointers to the start.

It should be fine if I pass bytes to `add_field` method.
