### ISSUE TITLE
Feature request: Add stop_after_attempt for testing purposes

### ISSUE THREAD

**Issue by oren0e** [inyutin/aiohttp_retry#62]
Hi, awesome library!

I would want a feature that I can instruct the retrying to stop after the `stop_after_attempt` attempt. This is mainly for testing because I don't want to wait the whole "production_attempt_times" times just to test that the retrying works in my service.
A similar feature can be found in `tenacity` library.

Thanks!

**Comment by inyutin** [comment]
@oren0e Hi!

May you please suggest interface for that? How you see it? 
Right now you can pass RetryOptions both to client and request

Anyway you will need to specify number as a param. Why not specify already existing ```attempts``` param?

**Comment by inyutin** [comment]
However I just add retry_options as a property. Maybe this will help you.
Look test here:
https://github.com/inyutin/aiohttp_retry/commit/4f36bbb90db3e625ef9d1a223e5612f848d8ba7f

You make do it like this
```python
client = get_default_client() # default has 5 attempts

client.retry_options.attempts = 2  # we don't make 5, let's only 5
client.get('url') as response 
....
```

If this still is not what you want - please provide me an interface you want

**Comment by inyutin** [comment]
I will close this for now, but feel free to reopen
