### ISSUE TITLE
Type "RetryClient" is no longer compatibe to "ClientSession"

### ISSUE THREAD

**Issue by ScholliYT** [inyutin/aiohttp_retry#69]
Hi there,

after upgrading from `aiohttp-retry==2.3.5` to `aiohttp-retry==2.5.1` (and `aiohttp==3.7.4.post0` to `aiohttp==3.8.1`) I get an error running `mypy` on my project. It says that the returned RetryClient is no longer compatible to aiohttp's ClientSession. Uprading everything except `aiohttp-retry` results in no error. However, I can't figure out what is wrong. Any ideas?

This seems to be caused by the changes from v2.4.5 to v2.5.6 (see changes here https://github.com/inyutin/aiohttp_retry/compare/v2.4.5...v2.5.6).

## Reproduce / Context
This is the file where the typecheck error happens: https://github.com/ScholliYT/Broken-Links-Crawler-Action/blob/431c545877d4e79612b4488bc226c54b5c58a795/deadseeker/clientsession.py

The MR where I updated everything: https://github.com/ScholliYT/Broken-Links-Crawler-Action/pull/22

MyPy run: https://github.com/ScholliYT/Broken-Links-Crawler-Action/runs/7297917680?check_suite_focus=true

**Comment by inyutin** [comment]
@ScholliYT thank you, that's interesting
Will make an eye on it a bit later

**Comment by inyutin** [comment]
@ScholliYT 

Hello! it's quite a strange bug!
The thing is aiohttp_retry was never compatible with ClientSession.
You can see exactly v2.3.5 code here:
https://github.com/inyutin/aiohttp_retry/blob/v2.3.5/aiohttp_retry/__init__.py
```python
class RetryClient:
    def __init__(
        self,
        logger: Optional[_Logger] = None,
        retry_options: RetryOptionsBase = ExponentialRetry(),
        raise_for_status: bool = False,
        *args: Any, **kwargs: Any
    ) -> None:
```

I have no suggestion why might it work to you previously. Maybe strange bug with mypy or your project configuration?

**Comment by inyutin** [comment]
@ScholliYT I have added 
```ClientType = Union[ClientSession, RetryClient]```

Maybe you want to use it.
