### ISSUE TITLE
RetryClient._make_requests() got an unexpected keyword argument 'auth'

### ISSUE THREAD

**Issue by philipnbbc** [inyutin/aiohttp_retry#79]
It appears that the latest release, 2.8.0, and this commit https://github.com/inyutin/aiohttp_retry/commit/2498b13d24eaf5121340d5e1791f9ea73be4d672 has broken the API. The requests no longer accept args such as `auth`.

The modified example code below fails with error: `TypeError: RetryClient._make_requests() got an unexpected keyword argument 'auth'`

```
import asyncio
import aiohttp
from aiohttp_retry import RetryClient, ExponentialRetry

async def main():
    auth = aiohttp.BasicAuth("username", "password")
    retry_options = ExponentialRetry(attempts=1)
    retry_client = RetryClient(raise_for_status=False, retry_options=retry_options)
    async with retry_client.get("https://example.com", auth=auth) as response:
        print(response.status)
        
    await retry_client.close()

asyncio.run(main())
```

**Comment by inyutin** [comment]
That's awful. Fixing it. Thanks for spotting out. 
The lack of test :(

**Comment by inyutin** [comment]
@philipnbbc @kozlovit 

Sorry for that. Use 2.8.1, it's fixed.
And thank you once again for reaching me out

https://github.com/inyutin/aiohttp_retry/commit/29248a53f927a5dfd39ca35673a52bdbb6e46f40

**Comment by inyutin** [comment]
actually not, fixing another

**Comment by inyutin** [comment]
Now everything should be fixed

**Comment by philipnbbc** [comment]
Thanks for the quick fix!
