### ISSUE TITLE
Question: is there a way to add total timeout?

### ISSUE THREAD

**Issue by roeeklinger** [inyutin/aiohttp_retry#84]
Hello,

I noticed that if I add the normal `aiohttp.ClientTimeout(total=3)` setting to either the `Client class` or to one of the `methods`, the total timeout seems to be ignored, instead, I get a `timeout error` appears for each request.

Is there a way to set a hard limit on the amount of time all the requests can take in total with this library?

**Comment by inyutin** [comment]
Hello, @roeeklinger 

Can you, please, provide an example?
This parameter should not be ignored and I don't see a way it can be. However, if you reduce total timeout - of course, you will face ```timeout error``` in case of no response. Each request will take up to ```aiohttp.ClientTimeout(total=3)``` seconds.

Maybe there is a misunderstanding of "total timeout". What do you mean by this word?

**Comment by inyutin** [comment]
feel free to re-open
