### ISSUE TITLE
Allow to retry based on HTTP Method

### ISSUE THREAD

**Issue by Legion2** [inyutin/aiohttp_retry#86]
In general HEAD, GET, OPTIONS, and PUT requests have no side effects and are therefore safe to retry. However, POST requests implement by definition side effects and retrying them can cause undesired side effects (e.g. duplicate entries). So there should be a way to configure which requests based on the HTTP method should be retried and which not.

**Comment by inyutin** [comment]
Hello @Legion2, this feature is available by v2.9.0 
https://github.com/inyutin/aiohttp_retry/pull/103
