### ISSUE TITLE
json.decoder.JSONDecodeError not triggering query retry

### ISSUE THREAD

**Issue by brubsby** [inyutin/aiohttp_retry#95]
I have the following code:

```python
import asyncio
import json

import aiohttp
import aiohttp_retry

NO_RETRY_CODES = {200, 500, 501}
RETRY_CODES = set(filter(lambda x: x not in NO_RETRY_CODES, range(100, 600)))
RETRY_EXCEPTIONS = {json.JSONDecodeError, aiohttp.client_exceptions.ServerDisconnectedError}

async def async_single(session, query):
    async with session.get(ENDPOINT, params={"query": str(query)}) as response:
        return query, await response.json(content_type=None)

async def async_batch(queries):
    tasks = []
    retvals = {}
    connector = aiohttp.TCPConnector(limit_per_host=5)
    async with aiohttp_retry.RetryClient(
            connector=connector,
            retry_options=aiohttp_retry.ExponentialRetry(
                attempts=10,
                statuses=RETRY_CODES,
                exceptions=RETRY_EXCEPTIONS)) as session:
        for query in queries:
            tasks.append(async_single(session, query))
        i = 0
        for val in asyncio.as_completed(tasks):
            key, val = await val
            retvals[key] = val
            while queries[i] in retvals:
                yield retvals[queries[i]]
                i += 1
                if i >= len(queries):
                    raise StopAsyncIteration
```

The tail end of the code is basically to start running all tasks at once, but yielding results as they appear in order, and this is the best way I've found to do it. (though it's very possible I'm missing an asyncio static function that does this)

But this works as expected, except the website I'm querying sometimes returns status code 200, but with a message in the response content that is not json parseable, explaining why the query failed. If this happens, I especially want the retrying logic to work, but passing json.decoder.JSONDecodeError into the exceptions param for the RetryClient doesn't seem to "proc" a retry in this case. Perhaps because we're doing the json decoding outside of the `session.get(...)` call.

Is this a limitation of the framework, or is there some feature I'm missing that could help me deal with this?

**Comment by inyutin** [comment]
Hello, @brubsby 

You are totally right in your findings. In your first message retry doesn't happen, because it's happening outside of the client. I think the way you did this in your second message via evaluate_response_callback is the way to go. 

I think we should not do anything with it, I believe the behaviour of the library is correct and documentation should be clear enough on this matter.
